Newapp/urls.py
from django.conf.urls import url
from . import views


app_name='Newapp'

urlpatterns=[
    url(r'ThanksForRegistering',views.thanks,name='thanksforregistering'),
    url(r'^export/$', views.download, name='download'),
    url(r'^Download/', views.extract, name='extract'),
]

Newproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from Newapp import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^$', views.base,name='base'),
    url('Kritagya18/',include('Newapp.urls'))
]

Newapp/models.py
from django.db import models

# Create your models here.

class Branches(models.Model):
    Branch=models.CharField(max_length=5)

    def __str__(self):
        return str(self.Branch)

class Register(models.Model):
    Name=models.CharField(max_length=50)
    Email=models.EmailField()
    Roll=models.PositiveIntegerField()
    Branch=models.OneToOneField(Branches,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.Roll)

Newapp/forms.py
from django import forms
from Newapp.models import Register


class RegisterForm(forms.ModelForm):
    class Meta():
        model=Register
        fields=('Name','Email','Roll','Branch')
        widgets = {
            'Name': forms.TextInput({'placeholder': 'Enter Name'}),
            'Email': forms.TextInput({'placeholder': 'Enter Email'}),
            'Roll': forms.TextInput({'placeholder': 'Enter Roll No'}),
        }

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['Name'].label = 'NAME'
        self.fields['Email'].label = 'EMAIL'
        self.fields['Roll'].label = 'ROLL NO'
        self.fields['Branch'].label = 'BRANCH'

Newapp/views.py
from django.shortcuts import render
from Newapp.models import Register
from django.http import HttpResponse,HttpResponseRedirect
from Newapp.forms import RegisterForm
from django.urls import reverse
import xlwt
# Create your views here.


def base(request):
    if request.method == "POST":
        form = RegisterForm(request.POST,label_suffix='')
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('Newapp:thanksforregistering'))
    else:
        form = RegisterForm(label_suffix='')

    return render(request,'Newapp/base.html',{'form':form})

def thanks(request):
    return render(request,'Newapp/thanks.html')

def download(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="registered.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Users')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['NAME', 'EMAIL', 'ROLL NO','BRANCH']

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Register.objects.all().values_list('Name', 'Email', 'Roll','Branch')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response

def extract(response):
    return render(response,'Newapp/download.html')

templates/Newapp/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'Newapp:download' %}">Registered people</a>
</body>
</html>

templates/Newapp/thanks.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

   <!--- basic page needs
   ================================================== -->
   <meta charset="utf-8">
	<link rel="shortcut icon" href="{% static 'Kritagya.png' %}">
	<title>Kritagya</title>
	<meta name="description" content="">
	<meta name="author" content="">

   <!-- mobile specific metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

 	<!-- CSS
   ================================================== -->
   <link rel="stylesheet" href="{% static 'css/base.css' %}">
   <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
   <link rel="stylesheet" href="{% static 'css/main.css' %}">

   <!-- script
   ================================================== -->
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/pace.min.js' %}"></script>
</head>
<style>
    .container {
    position: relative;
    text-align: center;
    color: white;
    width:100%
}

/* Bottom left text */
.bottom-left {
    position: absolute;
    bottom: 8px;
    left: 16px;
}

/* Top left text */
.top-left {
    position: absolute;
    top: 8px;
    left: 16px;
}

/* Top right text */
.top-right {
    position: absolute;
    top: 8px;
    right: 16px;
}

/* Bottom right text */
.bottom-right {
    position: absolute;
    bottom: 8px;
    right: 16px;
}

/* Centered text */
.centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
</style>
<body style="    font-family: "librebaskerville-regular", serif;
    font-size: 1.6rem;
    line-height: 3rem;
    color: #ffffff;">
<div class="container">
  <img src="{% static 'images/faculty.jpg' %}" alt="Snow" style="width:100%;">
  <div class="centered" style="margin-top:100px">
      <font color="#ffffff" size="100px">Thanks for Registering</font>
  </div>
    <div class="centered" style="margin-top:150px">
      <font><a href="{% url 'base' %}" style="color:#ffffff"> Go to Home</a></font>
  </div>
</div>
</body>

</html>